include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_import: true
    unused_import: true

analyzer:
  errors:
    unused_import: warning
    unused_shown_name: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
